### ISSUE TITLE
Compilation of new cases

### ISSUE THREAD

**Issue by themistella** [globaldothealth/monkeypox#104]
Hi all,
For your information in case it was missed, I noticed on Twitter that @RolandBakerIII does a daily thread on new cases, or adds new cases to another of his tweets of the day, and he's doing a pretty good job of it too. Well worth checking daily.
So I won't be doing too much research for a while, unless I notice some missing cases, as there's no use in duplicating efforts, and I also have other concerns to deal with.
Kind regards to all.
themistella

**Comment by themistella** [comment]
As luck would have it, the moment I say I'm taking a step back, I find three new countries, Taiwan, Croatia and Colombia. Typical 😂 See my Twitter posts.

**Comment by themistella** [comment]
French Guyana - Monkeypox - The two suspected cases have been discarded, tests were negative.

https://la1ere.francetvinfo.fr/guyane/pas-de-variole-du-singe-en-guyane-1289848.html

**Comment by themistella** [comment]
Bahamas - The monkeypox suspected case should be discarded. The patient was airlifted to Florida, USA. Therefore, if he did suffer from monkeypox, it's likely he will have been included in the count for Florida. 

More details at link:

http://www.tribune242.com/news/2022/jun/13/suspected-monkeypox-patient-airlifted-out-country/?news

**Comment by aimeehan1** [comment]
Thank you, @themistella. We've changed status for the Bahamas suspected case and made note of the circumstances.

**Comment by aimeehan1** [comment]
Thank you, @themistella. We have changed status for the 2 French Guiana cases.

**Comment by themistella** [comment]
Paraguay - Government stated that two suspected cases (we have one, case number 891) were discarded. Document is here:

https://dgvs.mspbs.gov.py/webdgvs/files/img/monkeypox/MonkeyPoxPY7_0.PDF

For you @aimeehan1 ?

Kind regards
themistella

**Comment by aimeehan1** [comment]
Hi @themistella. You tagged the right person. I've added to the curation queue.

**Comment by aimeehan1** [comment]
@themistella Paraguay has been updated. 2 discarded cases (ID 891, 7190). We appreciate your contributions.
