### ISSUE TITLE
Add endemic cases

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#116]
Add endemic cases from the Google sheet to CSV export, map and daily report.

- [x] PR to add endemic cases (monkeypox). Non-endemic cases will have a ID prefix 'N', endemic cases will have a prefix 'E'. **Do not merge**
- [x] Map aggregation: by default all cases endemic or non-endemic will be treated the same. If this is the expected behaviour, nothing to do. If not, filter out endemic and non-endemic cases separately
- [x] Briefing report: filter out endemic cases
- [ ] Briefing report: create a separate figure 1 that includes both
- [x] Set switchover date, inform partners about impending change to IDs, to keep current behaviour, they can filter by ID first character (ideally start of week, like 2022-07-11)
- [x] Merge PR on monkeypox, monkeypox-viz, monkeypox-report

**Comment by maciej-zarzeczny** [comment]
It is also possible for me to filter endemic and non endemic cases on the frontend based on ID

**Comment by aimeehan1** [comment]
@maciej-zarzeczny @abhidg @marinanicole We are editing endemic case data. We realized that previous entries were incorrectly summed. 

For example, following WHO reporting, DRC has a *total* of 1,476 cases, which _includes_ 107 confirmed and 1,369 suspected. The wording of the WHO report is misleading, which led to the calculation error. Numbers are being updated. We can add a note to GitHub once completed. 

https://apps.who.int/iris/bitstream/handle/10665/358807/OEW26-2026062022.pdf
"From 1 January – 5 June 2022, the Democratic Republic of the Congo reported 1 476 suspected cases with 65 deaths (CFR 4.4%) from 103 health zones across 20 provinces. The most affected provinces in 2022 are: Sankuru (525 cases, 35.6%), Tshopo (198 cases, 13.4%), Maniema (182 cases, 12.3%), Tshuapa (123 cases,8.3%) and Sud-Ubangi (111 cases, 7.5%). At least 107 of the cases sampled were confirmed positive for monkeypox virus infection."

**Comment by aimeehan1** [comment]
Endemic data is now updated, notification added to GitHub home page. "Endemic data has been updated as of 2022-07-22 to accurately reflect confirmed/suspected/total cases from source reporting."
