### ISSUE TITLE
Update data from Peru

### ISSUE THREAD

**Issue by jmcastagnetto** [globaldothealth/monkeypox#120]
According to the Ministry of Health of Peru, there are 15 cases as of July 4 2022, Reference: https://www.gob.pe/institucion/minsa/noticias/629137-minsa-confirma-15-casos-de-personas-contagiadas-con-la-viruela-del-mono-en-lima-metropolitana (in Spanish)

See also: https://twitter.com/Minsa_Peru/status/1544038122824015875 and https://www.gob.pe/institucion/minsa/noticias/628859-comunicado-oficial-de-prensa-n-1011

(The procedures and protocols are at: https://www.dge.gob.pe/epipublic/uploads/alertas/alertas_202216_01_191123.pdf)

**Comment by aimeehan1** [comment]
Hello @jmcastagnetto. The G.h total for Peru is at 15 cases. Thanks for confirming data.
