### ISSUE TITLE
24 cases with wrong confirmation date (6942–6965, Switzerland)

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#121]
The 24 Cases 6942–6965 (Switzerland) are from Monday 2022-07-04 and also contain the cases for the weekend.

**Comment by tvarrelman** [comment]
Hi @TKrepo , thank you for bringing this to our attention. Unfortunately we do not have the Switzerland webpage archived from 2022-07-02 and 2022-07-03. If you have any further information on the case counts from those two dates, that would be fantastic. 

Thanks!

**Comment by TKrepo** [comment]
Don’t worry about the weekend, they update the page only on workdays. That’s why Monday’s case count was so high (24), it also contains the cases from Saturday and Sunday.
