### ISSUE TITLE
Peru: Official data source for Monkeypox information

### ISSUE THREAD

**Issue by jmcastagnetto** [globaldothealth/monkeypox#129]
The DGE (Dirección General de Epidemiología, aka "CDC Peru"), has a page where they are frequently publishing updates on the number of cases, and related indicators for the Monkeypox infections in Peru: https://www.dge.gob.pe/portalnuevo/vigilancia-epidemiologica/subsistema-de-vigilancia/zoonoticas/viruela-del-mono/

This can be a source you could use to track the spread of this disease. For example, for the epiweek 28, they report 64 cases for Peru.

**Comment by aimeehan1** [comment]
Thank you @jmcastagnetto. We've found Minsa's Twitter feed a helpful source for the latest MPX information, too. I've added this DGE source to the GitHub Wiki page, where we have a list of frequently checked sources by country.
