### ISSUE TITLE
Discussion on data schema

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#13]
Discussion about the data schema. 

Suggestions: 

a) include vaccination status, vaccination date.
b) include case definition during time of data being reported.

**Comment by TKrepo** [comment]
I would be interested in where hospitalizations occur for medical necessity and where as a means for isolation.

**Comment by fitznerj** [comment]
Would add info if data comes from aggregated data and sources with classification ministry of health or media

**Comment by abhidg** [comment]
Line list is discontinued as of 2022-09-22
