### ISSUE TITLE
Source data

### ISSUE THREAD

**Issue by aimeehan1** [globaldothealth/monkeypox#131]
Is there a way to provide a hyperlink for the source? When the source is saved by the system, will it save the source reference or just source text?

Example: GoogleSheet_Endemic Countries Tab, Nigeria Data. We use the hyperlink text as a way to notify the user what report number was used for that row of data entry. Example: "NCDC Week 8 report"

**Comment by jim-sheldon** [comment]
Looking at the last-generated .csv I see URLs and no source text (e.g. "NCDC Week 8 report").
I can see that the Nigeria CDC site provides links to the reports for each week.
The data ingestion script saves sources as .pdfs (including trying to convert webpages) and backs them up to S3, so including the full link to .pdfs will result in those getting snapshotted.
Would it be OK to do that and move the hyperlink text to the "Notes" column?

**Comment by aimeehan1** [comment]
Hyperlinks were removed from source column, replaced with PDF links.
