### ISSUE TITLE
Spreadsheet empty - broken

### ISSUE THREAD

**Issue by theonikl** [globaldothealth/monkeypox#134]
![image](https://user-images.githubusercontent.com/108159207/181340180-7735f3a3-671d-451f-8d97-4c54a1f45f22.png)
Error (result too large) 
This happens because importrange has too many cells

**Comment by theonikl** [comment]
You can split the importrange to 2 or 3 pieces. For example importrange for cell 1-10000 another for 10001 to 20000 etc

**Comment by jim-sheldon** [comment]
Hi @theonikl, thanks for reporting the issue and suggesting a fix. The sheet should work as expected now.
