### ISSUE TITLE
Country/WHO/ECDC Case definitions 

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#14]
Adding case definition and store in folder on this repository.

**Comment by Mougk** [comment]
USA: https://www.cdc.gov/poxvirus/monkeypox/pdf/Monkeypox-Exposure-Questionnaire.pdf

**Comment by Mougk** [comment]
UKHSA (as of May 23, 2022): Confirmed case 


"A person with a laboratory confirmed monkeypox infection (monkeypox PCR positive)


Probable case 

A person with a monkeypox compatible vesicular-pustular rash plus at least one of the following epidemiological criteria:

Exposure to a confirmed or probable case in the 21 days before symptom onset
History of travel to an area where monkeypox is endemic, or where there is a current outbreak in the 21 days before symptom onset (currently West and Central Africa, Spain, Portugal and USA)
Gay, Bisexual and Men who have Sex with Men (GBMSM) 

Possible case 

A person with a febrile prodrome* compatible with monkeypox infection where there is known prior contact with a confirmed case in the 21 days before symptom onset 

OR

A person with an illness where the clinician has a high suspicion of monkeypox (for example, this may include prodrome or atypical presentations with exposure histories deemed high risk by the clinician, or classical rash without risk factors)"

**Comment by Mougk** [comment]
WHO Surveillance, case investigation and contact tracing for Monkeypox: 

https://apps.who.int/iris/bitstream/handle/10665/354486/WHO-MPX-Surveillance-2022.1-eng.pdf?sequence=1&isAllowed=y

**Comment by Mougk** [comment]
ECDC Case Definitions: https://www.ecdc.europa.eu/sites/default/files/documents/Monkeypox-multi-country-outbreak.pdf

**Comment by Mougk** [comment]
Case definition Morocco: https://www.h24info.ma/maroc/sante-voici-le-protocole-national-du-maroc-contre-la-variole-du-singe/

Case definition University of Geneve: https://www.hug.ch/sites/interhug/files/structures/centre_maladies_virales_emergentes/monkeypox_hug_fr_21.05.2022.pdf

Case definition France attached:
[def_cas_CAT_monkeypox_20052022.pdf](https://github.com/globaldothealth/monkeypox/files/8760597/def_cas_CAT_monkeypox_20052022.pdf)

**Comment by Mougk** [comment]
Spain: https://www.sanidad.gob.es/profesionales/saludPublica/ccayes/alertasActual/alertaMonkeypox/docs/ProtocoloMPX_2022.05.20.pdf

**Comment by sumalibajaj** [comment]
Canada:
http://www.bccdc.ca/health-professionals/clinical-resources/monkeypox#:~:text=Last%20updated%3A%20May%2019%2C%202022,smallpox%20but%20is%20less%20severe.

**Comment by Mougk** [comment]
Updated case definition for France

[def_cas_CAT_monkeypox_25052022.pdf](https://github.com/globaldothealth/monkeypox/files/8779639/def_cas_CAT_monkeypox_25052022.pdf)

**Comment by Mougk** [comment]
Ontario: https://www.coto.org/docs/default-source/default-document-library/cmoh-77-6-order-monkeypox.pdf?Status=Temp&sfvrsn=5615b1cc_2

Netherlands: https://lci.rivm.nl/richtlijnen/pokken


PAHO: [2022-MAY-20-PHE-Epi-Alert_Monkeypox_EN.pdf]
(https://github.com/globaldothealth/monkeypox/files/8781552/2022-MAY-20-PHE-Epi-Alert_Monkeypox_EN.pdf)

**Comment by Mougk** [comment]
Northern Ireland: https://www.hpsc.ie/a-z/zoonotic/monkeypox/guidance/Monkeypox%20Clinicians%20Public%20Health.pdf
Mexico: https://www.gob.mx/cms/uploads/attachment/file/728064/AE_Viruela_Simica_240522.pdf
Uruguay: https://www.crmpr.org.br/uploadAddress/Comunicacao-de-Risco-06-Monkeypox-22-05-22-FINAL[5321].pdf

**Comment by Mougk** [comment]
USA update from May 25, 2022: https://www.cdc.gov/poxvirus/monkeypox/clinicians/case-definition.html

Italy as of May 25, 2022: https://www.trovanorme.salute.gov.it/norme/renderNormsanPdf?anno=2022&codLeg=87420&parte=1%20&serie=null

**Comment by Mougk** [comment]
Brazil: https://www.crmpr.org.br/uploadAddress/Comunicacao-de-Risco-06-Monkeypox-22-05-22-FINAL[5321].pdf

**Comment by Mougk** [comment]
Switzerland - Vaud Canton : https://www.hpci.ch/prevention/recommandations/contenu/monkeypox-recommandations-g%C3%A9n%C3%A9rales-prise-en-charge-des-malades

**Comment by Mougk** [comment]
Iceland: https://www.landlaeknir.is/servlet/file/store93/item49659/Lei%C3%B0beiningar%20fyrir%20heilbrig%C3%B0isstarfsf%C3%B3lk_27.05.2022.pdf

**Comment by Mougk** [comment]
Denmark: https://www.sst.dk/-/media/Udgivelser/2022/Abekopper/Retningslinjer-for-haandtering-af-abekopper-i-Danmark-v3.ashx?sc_lang=da&hash=F9B97DCE2FC9B2BD7ECEE36991DC4681

**Comment by Mougk** [comment]
Peru July 2nd: https://cdn.www.gob.pe/uploads/document/file/3346360/Norma%20T%C3%A9cnica%20de%20Salud%20para%20la%20Prevenci%C3%B3n%20y%20Manejo%20de%20los%20Pacientes%20Afectados%20por%20Viruela%20del%20Mono.pdf

**Comment by jmcastagnetto** [comment]
@Mougk for Peru, in addition to the technical document you mentioned, there is also the Epidemiological alert (https://www.dge.gob.pe/epipublic/uploads/alertas/alertas_202216_01_191123.pdf) which includes the relevant forms been used to capture the details of where the disease affects the patient, possible place where he/she got infected, etc.
