### ISSUE TITLE
monkeypox-report: drop public URLs, refer to filename instead

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#140]
**Describe the bug**
https://github.com/globaldothealth/monkeypox-report currently uses archives from GitHub for reproducibility purposes and writes them to index.json. This gives us a way to reproduce reports on a particular day. As archives are going to be imminently removed from GitHub due to the S3->GitHub script failing to import large amounts of data, this will mean that no public URLs are available for monkeypox-report.

**Proposed solution**
Either making monkeypox bucket public globaldothealth/monkeypox#141 or disabling reproducibility and using a secret key to get access to the private bucket.

**Comment by jim-sheldon** [comment]
I think using a secret key makes sense.
