### ISSUE TITLE
No update on new latest.json

### ISSUE THREAD

**Issue by Toni-99** [globaldothealth/monkeypox#143]
Since friday, there were no new updates on this and the latest.csv file. Can you please check here? :)

**Comment by abhidg** [comment]
Thanks for reporting @Toni-99! fixed

**Comment by roelgrif** [comment]
When will https://raw.githubusercontent.com/owid/notebooks/main/EdouardMathieu/monkeypox/owid-monkeypox-data.csv be updated?

**Comment by abhidg** [comment]
@roelgrif That's OWID data, downstream from us

**Comment by roelgrif** [comment]
OK, apart from that, the last three days seem far from complete in latest.csv

**Comment by jim-sheldon** [comment]
The job that puts data in the S3 bucket broke, making both the `latest.csv` there and its replicant in this repo out of date. Reopening this issue.

**Comment by jim-sheldon** [comment]
Fixed the job by increasing its timeout.
