### ISSUE TITLE
Lack of symptom data

### ISSUE THREAD

**Issue by a-hsu** [globaldothealth/monkeypox#152]
Just starting to get into this repo (thanks to all for the data collection btw!). I was curious as to why only 189 cases with symptoms were written down. Are symptoms just not reported, so we can't get that data anywhere? Thanks.

**Comment by aimeehan1** [comment]
Hello @a-hsu. Thanks for reaching out to G.h. We record symptom data when provided by the source and attributable to a single case in our line-list. We do not capture symptom data when it is provided for aggregate cases by the source -- for example, "X% of cases had fever." Most often, we cannot decipher which case(s) they are referencing in our line-list to record the symptom. If you are interested in researching a certain country, you can review our WIKI list of frequently checked sources by country and search for their symptom data. https://github.com/globaldothealth/monkeypox/wiki 
Let us know if you have further questions.
