### ISSUE TITLE
Multiple entries for the same location - Example France

### ISSUE THREAD

**Issue by theonikl** [globaldothealth/monkeypox#155]
Auvergne-Rhone-Alpes
Bourgogne-Franche-Comte
Brittany
Brittany
Central Val de Loire
Centre Val de Loire
Centre-Val de Loire
Corsica
Grand Est
Hauts de France
Hauts-de-France
Ile-de-France
île-de-France
Lyon, Auvergne-Rhone-Alpes
Marseille, PACA
Normandie
Normandy
Normandy
Nouvelle Aquitaine
Nouvelle-Aquitaine
Occitania
Occitanie
Occitanie
Paca
Pays de la Loire
Pays-de-la-Loire
Toulouse, Occitanie
Vannes, Brittany

**Comment by aimeehan1** [comment]
Hi @theonikl -- Thanks for reaching out. We're doing our best to stay up-to-date with country counts and will need to dedicate time and resources to data cleaning soon.  Occitania/Occitanie, Paca/PACA etc. will still refer to the same province.  G.h counts by province match France's .gov source count. @tvarrelman
