### ISSUE TITLE
Official data source (dashboard) for Peru with details to District level

### ISSUE THREAD

**Issue by jmcastagnetto** [globaldothealth/monkeypox#156]
Since yesterday (2022-08-06), the Ministry of Health of Peru (MINSA) has a dashboard showing the cases for Monkeypox in Peru (Ref: https://elperuano.pe/noticia/177147-minsa-lanza-sala-situacional-para-informar-sobre-casos-diarios-de-viruela-del-mono). 

The dashboard seems to have only cumulative numbers, but if you get them periodically, it might be a good way to build a timeseries.

The dashboard is at: https://www.dge.gob.pe/sala-monkeypox/

Hope this helps.

**Comment by aimeehan1** [comment]
@jmcastagnetto Thank you! I have added the DGE dashboard to our frequently checked sources WIKI page. https://github.com/globaldothealth/monkeypox/wiki
