### ISSUE TITLE
Compare agency data against each other

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/monkeypox#170]
We should create a script that aggregates case counts from each agency and outputs a report showing the differences in each data set. If possible, it would be ideal to compare archives too.

**Comment by oliszymanski** [comment]
you mean creating a  correlation and mean between two different data types? I think it would be cleaner with that data displayed

**Comment by ksewalk** [comment]
@oliszymanski this is outside the scope of this ticket. But you are welcome to open a new ticket with the request for the team to review for consideration. Check out the scripts folder for a pattern that is reusable.
