### ISSUE TITLE
Datasets with .csv.gz format

### ISSUE THREAD

**Issue by lisphilar** [globaldothealth/monkeypox#180]
Is it possible to provide datasets with .csv.zip format (or another compressed file format)?

Because the number of records will be increased sharply, downloading task will be more and more time-consuming and high network load task.

**Comment by jim-sheldon** [comment]
Yeah, we can add compression to and save a new latest.csv.gz or something similar.

**Comment by jim-sheldon** [comment]
Closing as this will be already done with the pathogen-agnostic portal.
