### ISSUE TITLE
New case in Hong Kong

### ISSUE THREAD

**Issue by clementsun** [globaldothealth/monkeypox#181]
https://www.news.gov.hk/eng/2022/09/20220906/20220906_174009_102.html

First imported case in Hong Kong. 30 years old male arrived Hong Kong from the Philippines on September 5.
Confirmed with monkeypox on September 6. Has sore throat, difficulty in swallowing, skin rash and lymphadenopathy.
Had travelled to the US and Canada between August 2 and September 2.

**Comment by jim-sheldon** [comment]
This case appears to have been added. Please reopen this issue if I made a mistake.
