### ISSUE TITLE
Users may download one G.h file (WHO+CDC)

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#185]
We need to regularly update G.h's data set to include WHO and CDC case counts. For CDC, this is US/state-level case counts; for WHO it is all other countries.

**Comment by jim-sheldon** [comment]
Since one data set includes state-level data and the other does not, using the day zero schema might make the most sense.

**Comment by jim-sheldon** [comment]
While we do not have a time series file for state-level case data, we will be able to provide one once we get data into the system. We could use the confirmation date value for it.
