### ISSUE TITLE
Notify data partners of changes

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#186]
## Description

includes ReadMe update

**Comment by aimeehan1** [comment]
@abhidg @ksewalk Input welcome!

DRAFT README: The G.h team completed a 100-day mission to provide decision makers, researchers, and the public with timely and accurate, openly-accessible line-list global data for the 2022 MPX outbreak. Now, we are at a point of transition. On 2022-09-23, the G.h team will start to provide the latest MPX data from the World Health Organization (global) and the United States Center for Disease Control and Prevention (U.S. data only).  G.h MPX line-list data, last updated 2022-09-22, will remain accessible via download through GitHub. We thank our user community for their many helpful contributions and for identifying G.h a trusted source of information.

**Comment by ksewalk** [comment]
@aimeehan1 slight edits:

> The Global.health team completed a 100-day mission to provide decision makers, researchers, and the public with timely and accurate, openly-accessible global line-list data for the 2022 Monkeypox outbreak. Now, we are at a point of transition. On 2022-09-23, the Global.health team will begin providing the latest Monkeypox data from the World Health Organization (global) and the United States Center for Disease Control and Prevention (U.S. data only). Global.health Monkeypox line-list data, last updated 2022-09-22, will remain accessible via download through GitHub. We thank our user community for their many helpful contributions and for identifying Global.health as a trusted source of information.

**Comment by aimeehan1** [comment]
@ksewalk Looks great. I'm planning to use this "100-day mission" angle for the newsletter piece.

**Comment by aimeehan1** [comment]
@jim-sheldon

**Comment by aimeehan1** [comment]
The Global.health team completed a 100-day mission to provide decision makers, researchers, and the public with timely and accurate, openly-accessible, global line-list data for the 2022 monkeypox outbreak. Now, we are at a point of transition. On 2022-09-23, the Global.health team will shift from providing manually-curated line-list data to openly-available data resources, compiling downloadable monkeypox datasets from the World Health Organization, U.S. Centers for Disease Control and Prevention, and the European Centre for Disease Control and Prevention. Global.health monkeypox line-list data, last updated 2022-09-22, will remain accessible via download through GitHub. We thank our user community for their many helpful contributions and for identifying Global.health as a trusted source of information.​

**Comment by aimeehan1** [comment]
README updated; newsletter sent to users on 2022-09-21.
