### ISSUE TITLE
Users can download single dataset from each agency

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#187]
We need a script that ingests data from different agencies (CDC, ECDC, WHO), and our web UI to expose that data for download.

MVP could be ingesting CSV files to S3 directly. If possible we should use a database.

**Comment by aimeehan1** [comment]
@jim-sheldon I confirmed that we should exclude PAHO from user-download.

**Comment by jim-sheldon** [comment]
Created https://github.com/globaldothealth/monkeypox/issues/197 for work on ingesting directly to the database.
