### ISSUE TITLE
Update MPX briefing report

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#188]
@aimeehan1 to determine if briefing report is needed to be continued. Perhaps point to WHO briefing report (need to create a new ticket if we go down that path)

If we decide to keep the briefing report, it will need to be updated with the new MPX data source

**Comment by aimeehan1** [comment]
@Mougk Can we end the G.h daily briefing report with the transition. Instead, we can point users to the WHO Global Trends report. https://worldhealthorg.shinyapps.io/mpx_global/

**Comment by abhidg** [comment]
Closing this, will re-open if we decide to start a new report for the WHO / CDC based data
