### ISSUE TITLE
Add country to dropdown

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#19]
Add:

a ) England 
b) Northern Ireland
c) Scotland
d) Wales

**Comment by ksewalk** [comment]
Work is in progress.

Mapbox uses ISO country codes, which map to United Kingdom only. We will aggregate UK cases on the map/website list, but will expand the spreadsheet dropdown to include England, Scotland, Northern Ireland, Wales. Will update spreadsheet dropdown once backend configuration for mapping the data is complete, so as not to break the map when data is uploaded.

**Comment by abhidg** [comment]
Thanks! Next version of the data should have ISO3 country codes as well which should make the map visualization easier.

**Comment by abhidg** [comment]
latest.csv and latest.json now have ISO3 codes.

**Comment by ksewalk** [comment]
wonderful thanks @abhidg!
