### ISSUE TITLE
Update MPX US state level map

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#190]
## Description

Explore breaking out the MPX Map view to visualize state level data

**Comment by aimeehan1** [comment]
@ksewalk @abhidg Recommend display of U.S. country-level data for ease of transition and map consistency. Can discuss possibility to display geographic granularity (state-level counts) at later date.

**Comment by ksewalk** [comment]
Aimee, that sounds like a good plan to me. Moving this issue to the backlog and we can revisit at a later date.

**Comment by aimeehan1** [comment]
mpox visualization was maintained at the country-level for all countries/ territories for consistency. Curation ended in September 2022.
