### ISSUE TITLE
Newsletter update 

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#192]
To discuss impact of first 100 days + new MPX direction

**Comment by ksewalk** [comment]
Can link to the papers based on our dataset: https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=github.com%2Fglobaldothealth%2Fmonkeypox&btnG=

**Comment by aimeehan1** [comment]
DRAFT for review: https://docs.google.com/document/d/1j2uIrR4SsndfCMUZnCot7xcbSoIlUCu0_RYm_UPLpII/edit?usp=sharing
