### ISSUE TITLE
Sunset infrastructure for MPX

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#193]
Sunset necessary infrastructure running for MPX line list data ingestion

Includes:
- [x]  Slack bot notifications (update as needed for new data input)
- [x]  Automated MPX report [dependent on decision made in issue #188]
- [x]  Put notice in ReadMe
- [x]  Put notice in spreadsheet
- [x]  Quality Checks (is one needed for WHO data, i.e. if ingestion fails)
- [x] AWS stuff (terraform)

**Comment by aimeehan1** [comment]
ReadMe and Spreadsheet language suggested in Ticket #186

**Comment by ksewalk** [comment]
We will check in on this on D-DAY (Friday 9/23 9am EST / 2pm UK)
