### ISSUE TITLE
Put banner on map saying not updated after 2022-09-23

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#199]
Text: "Map based on line list will not be updated after 2022-09-23, see [notice]" @ksewalk @aimeehan1 can link to the GitHub notice / newsletter which will say that we plan to update the map based on WHO data in the near future

**Comment by aimeehan1** [comment]
@ksewalk @abhidg @Mougk DRAFT:   *Map and data are last updated 2022-09-22*. Our team completed a 100-day mission to provide early situational awareness through open-access, global line-list data for the 2022 monkeypox outbreak. The map will remain static as we transition. Check-out what's happening next with our data in GitHub [README​](https://github.com/globaldothealth/monkeypox).
