### ISSUE TITLE
Country = England vs United Kingdom

### ISSUE THREAD

**Issue by Mike-Honey** [globaldothealth/monkeypox#2]
Country is in general a ridiculous swamp for data collection, there are so many lists and definitions - any perspective could be "correct".

But IMO, United Kingdom would be a more appropriate value for Country, rather than England. Perhaps England could be recorded as an administrative region?

Feel free to ignore, as I mentioned this is a real swamp and your intent is already clear.

**Comment by Mougk** [comment]
https://en.wikipedia.org/wiki/England states that England is considered a country and health systems in Scotland, Wales, England are separate I'm inclined to leave like this for now.

**Comment by TKrepo** [comment]
By that logic, shouldn’t be [Scotland](https://en.wikipedia.org/wiki/Scotland) a country too? Frankly, I’d prefer to include them all into the country "United Kingdom".
