### ISSUE TITLE
Convention/standard for country names

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/monkeypox#200]
Do we want to use WHO country names, or ISO-3166, or continue with this map of WHO country names to ours:
{
	"Republic Of Korea": "South Korea",
	"Venezuela (Bolivarian Republic of)": "Venezuela",
	"Türkiye": "Turkey",
	"Bosnia And Herzegovina": "Bosnia And Herzegovina",
	"Czechia": "Czech Republic",
	"Bolivia (Plurinational State of)": "Bolivia",
	"Russian Federation": "Russia",
	"Saint Martin": "Saint Martin (French part)",
	"Republic Of Moldova": "Moldova",
	"Iran (Islamic Republic of)": "Iran"
}

**Comment by abhidg** [comment]
We should use ISO-3166 3 letter names everywhere, unless it is not possible.

**Comment by jim-sheldon** [comment]
I think it makes sense for us to use the WHO names: they are official/UN country names, we are only using WHO data, we need our data to be human-readable and our US line list cases include state and non-state names.
We will still use ISO-3166 country codes internally though.
