### ISSUE TITLE
latest.csv is not being refreshed (4 days old now)

### ISSUE THREAD

**Issue by roelgrif** [globaldothealth/monkeypox#211]
See subject.

**Comment by jim-sheldon** [comment]
Yep, thanks. The github action broke. Should be fixed now and not break for the same reason again.

**Comment by abhidg** [comment]
@roelgrif yes, we have transitioned from providing a line list to providing aggregated counts from WHO and CDC. The old line list is available at https://raw.githubusercontent.com/globaldothealth/monkeypox/main/latest_deprecated.csv

**Comment by roelgrif** [comment]
Ah, a pity, it broke my reporting module. I guess the deprecated version isn't updated anymore from now on?

**Comment by abhidg** [comment]
@roelgrif yes, the deprecated file will no longer be updated.

**Comment by roelgrif** [comment]
Thanks.
