### ISSUE TITLE
Generate output with ISO3 codes for map

### ISSUE THREAD

**Issue by jim-sheldon** [globaldothealth/monkeypox#221]
> Can we use the WHO ISO3 codes? Might make mapping simpler especially if the map also uses ISO3

Sure, I think we might want to make a separate script or output for that, so that we provide one user-facing, human-readable (definitely csv) data set, and one internal, machine-readable (probably json) data set.

_Originally posted by @jim-sheldon in https://github.com/globaldothealth/monkeypox/issues/219#issuecomment-1261027735_

**Comment by lisphilar** [comment]
We can use Python package `country_converter`. This is very useful for me in COVID-19 project.
https://github.com/konstantinstadler/country_converter

**Comment by abhidg** [comment]
With the WHO dataset, country names have been replaced with ISO codes in the monkeypox-aggregates bucket
