### ISSUE TITLE
latest.csv is empty

### ISSUE THREAD

**Issue by kootsoop** [globaldothealth/monkeypox#223]
![Screen Shot 2022-09-29 at 15 48 23](https://user-images.githubusercontent.com/82619/193128036-55226a7a-a623-4315-9b74-46b0ada89c6a.png)

**Comment by jim-sheldon** [comment]
Hello, on 2022-09-23, the Global.health team shifted from providing manually-curated line-list data to openly-available data resources, compiling downloadable monkeypox datasets with aggregate case data from the World Health Organization, U.S. Centers for Disease Control and Prevention. On 2022-09-23 the team deprecated the `latest.csv` file.

For more information please see our README, `.csv` files in the base directory of the project, and the contents of [the scripts folder.](https://github.com/globaldothealth/monkeypox/tree/main/scripts).

**Comment by lisphilar** [comment]
@jim-sheldon 
We have `latest.csv` and `latest_deprecated.csv` at the top directory. Just to confirm, they have different columns, but both of them are deprecated? This is confusing.

**Comment by jim-sheldon** [comment]
@lisphilar `latest.csv` gets automatically updated by a Github Action, `latest_deprecated.csv` is there in case someone wants it.
I apologize for any confusion, and am happy to address any questions or issues, and field input for how we can do better.
