### ISSUE TITLE
Bring back latest.json

### ISSUE THREAD

**Issue by Toni-99** [globaldothealth/monkeypox#242]
i started using your repo in a private project but now I need to rethink the whole structure. Is it possible to bring back the latest.json where we had attributes like age, source, country code etc.? :)

**Comment by abhidg** [comment]
We are not updating the latest.json anymore as we do not have age and source information from WHO / CDC which only provides aggregate counts.

If you are looking for the last published latest.json which will no longer be updated, then it is available at https://github.com/globaldothealth/monkeypox/blob/1.0/latest.json
