### ISSUE TITLE
data dictionary update for Status = excluded

### ISSUE THREAD

**Issue by Mike-Honey** [globaldothealth/monkeypox#25]
I noticed today that some rows appear with Status = excluded.  I imagine that typically these rows should be removed from any analysis of this data?

Could you update the data dictionary to clarify?

Thank you so much for this awesome dataset - I'm sure it's a huge effort.

**Comment by TKrepo** [comment]
It seems to me, that [excluded] is for cases, that were [suspected], but then were confirmed as negative.

It could be useful to calculate a positivity rate in those countries that communicate systematically all their suspected cases.
