### ISSUE TITLE
Monkeypox data for the Netherlands

### ISSUE THREAD

**Issue by mzelst** [globaldothealth/monkeypox#26]
Hi folks,

Thank you for creating this database on monkeypox cases worldwide. I maintain the largest database on Dutch covid-19 data but have added monkeypox case data as well for my own record keeping. 

I'm updating the data as they come in on my Github repo. I have reformatted the data into the template format that you provided. If you would like, you can pull the data and use it for your global database. The monkeypox data, in the template format as provided in the repo here, can be found here: https://github.com/mzelst/covid-19/blob/master/data-misc/monkeypox/monkeypox_globaldothealth.csv

Let me know if this works!

Kind regards,
Marino van Zelst

**Comment by Mougk** [comment]
Thank you --  do you have sources associated with each case? cc @abhidg

**Comment by Mougk** [comment]
thanks.

**Comment by Mougk** [comment]
I've added these now. We will keep monitoring your file here. Please re-open issue in case we miss some.
