### ISSUE TITLE
Monkeypox data for Italy

### ISSUE THREAD

**Issue by vi-enne** [globaldothealth/monkeypox#29]
Hi,
a quick update on Italian monkeypox cases.
With respect to the current version on your repo, two more cases have been confirmed and there is genomics information for the first three cases.

I will try to keep the file updated

https://docs.google.com/spreadsheets/d/1_3f41fVeCj8Fy9yXEWLYtDzgyzBsRCTp--BOfUsGl8A

**Comment by Mougk** [comment]
@outbreakprepared can you double check and merge files?

**Comment by ksewalk** [comment]
@abhidg @outbreakprepared - @marinanicole and @aimeehan1 are manually reviewing/entering these case entries. No file merge needed.

**Comment by vi-enne** [comment]
There is a new one in Emilia-Romagna.
Instead of opening new issues, I will keep the file as updated as possible, using your IDs.

Thanks!

**Comment by aimeehan1** [comment]
Data last updated by user 2022-06-14. Relevant metadata added to tracker. Closing ticket.
