### ISSUE TITLE
3 confirmation dates missing

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#3]
First of all, thanks a lot for maintaining this list! Here are a couple of things I’ve noticed:
[Date_confirmation] is missing for case [ID] 146 (Switzerland), 147 (Germany), 185 (Spain).
Currently BNO’s tracker (bnonews.com/monkeypox/)has 11 confirmed cases more (108 instead of 97) and mentions a suspected case in Greece.

**Comment by Mougk** [comment]
thank you -- have added the confirmation dates now. we have looked into the discrepancy and at least in part that's due to an update on confirmed cases in Portugal.

**Comment by TKrepo** [comment]
Ups, looks like you added the confirmation date for [ID] 146 (Switzerland) in the [Country] column.

**Comment by Mougk** [comment]
fixed.
