### ISSUE TITLE
Google Sheet for Germany (with sources)

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#37]
Maybe you’ve seen it already, somebody is mainting a [Google Sheet with cases in Germany](https://docs.google.com/spreadsheets/d/1p-_ufMx6F5ol32MFfes2vPVYzKWYiovxgCnHxEIpQOE/edit#gid=0), with locations and links to sources.

**Comment by aimeehan1** [comment]
Thanks @TKrepo. We've found this tracker to be a helpful cross-check for RKI numbers and for additional secondary sources with metadata. I've added the link to our GitHub WIKI, where we keep a list of frequently checked sources by country.
