### ISSUE TITLE
Google Sheet WITH JSON

### ISSUE THREAD

**Issue by abdalmalkiq** [globaldothealth/monkeypox#38]
I suggest to make it in json file  More organized, customizable, and easier to connect with all programming languages. When you put it in Google Sheet, it becomes a seat to connect and separate data when you turn it into a Json file that is filled with hundreds of lines and there is nothing important in it. It is preferable to host the Json file on your server and make data easy to read like in google sheet but in json

**Comment by abhidg** [comment]
We already have a JSON file: https://github.com/globaldothealth/monkeypox/blob/main/latest.json - did you mean something else? This can be parsed by any language that support JSON such as Python's `json.load()` function.
