### ISSUE TITLE
Missing [Date_confirmation]

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#39]
Confirmation dates are missing from yesterday’s confirmed cases from Portugal. (See [table here](https://github.com/globaldothealth/monkeypox/issues/4#issue-1244310570).)

**Comment by abhidg** [comment]
These are missing in the upstream spreadsheet, pinging curator team.

**Comment by ksewalk** [comment]
This is now updated. thank you for reporting!
