### ISSUE TITLE
Diff Table GH ±BNO and missing confirmation dates (if any)

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#4]
Country | Conf. GH ±BNO | Source
-- | -- | --
Denmark | 2   +2 | [sum.dk](https://sum.dk/nyheder/2022/juni/tre-danske-tilfaelde-af-abekopper)
Germany | 113   +18 | [rki.de](https://www.rki.de/DE/Content/InfAZ/A/Affenpocken/Ausbruch-2022-Situation-Deutschland.html;jsessionid=0FB3D1103449DE4FCC03AC160542D0F5.internet061?nn=2386228)
Gibraltar | 0   +1 | [chronicle.gi](https://www.chronicle.gi/gha-confirms-first-case-of-monkeypox-in-gibraltar/)
Greece | 0   +1 | [kathimerini.gr](https://www.kathimerini.gr/society/561901132/eylogia-ton-pithikon-to-proto-episimo-kroysma-stin-ellada-i-anakoinosi-toy-eody/)
Italy | 26   -2 | [ausl.pc.it](https://www.ausl.pc.it/news/1024/a-piacenza-accertati-tre-casi-di-monkeypox-collegati-tra-loro.html)
Spain | 225   +8 | [rtve.es](https://www.rtve.es/noticias/20220608/viruela-mono-sanidad-casos-total-espana/2370522.shtml)
UK | 322   -1 | [news.sky](https://news.sky.com/story/monkeypox-77-more-cases-detected-in-uk-taking-total-to-302-12628835)
  |   |  
Total | 1240   +30 -3 |  
  |   |  
Version | 2022-06-09 | 12:46 PM CEST

**Comment by Mougk** [comment]
Thanks. yes v helpful. Keep publishing here. I have double checked them all. We have a higher bar to include cases in our line list, hence some discrepancies to be expected.

**Comment by TKrepo** [comment]
I’ve added BNO's absolute numbers in parentheses. This should make it easier for you to see the differences that you’ve already examined and decided not to include.

BNO Country | confirmed | suspected
-- | -- | --
Belgium | +1 (4) | -1 (0)
Canada |   | +4 (22)
France |   | +1 (1)
Germany |   | +2 (2)
Israel |   | +1 (1)
Netherlands |   | +1 (1)
Spain |   | +1 (53)
UK |   | +1 (1)

**Comment by TKrepo** [comment]
Or is it perhaps easier for you to read if I use your (GH’s) count as the base number and add the ±difference behind it?

BNO Country | confirmed | suspected
-- | -- | --
Argentina |   | 0   +1
Austria | 0   +1 | 1   -1
Belgium | 3   +1 | 1   -1
Canada |   | 18   +4
France |   | 0   +1
Germany |   | 0   +2
Israel |   | 0   +1
Netherlands |   | 0   +1
Spain |   | 52   +1
UK |   | 0   +1

**Comment by TKrepo** [comment]
Do you get notified when I edit a comment?

**Comment by Mougk** [comment]
No but we can regularly check here.

**Comment by TKrepo** [comment]
I've added a column with the source sites (as links) so it’s easier for you to see which sources you’ve already rejected.

**Comment by vi-enne** [comment]
BNO has stopped updating [their tracker](https://bnonews.com/monkeypox/).

![image](https://user-images.githubusercontent.com/44818674/173238484-9c3dd5c8-7248-4fbf-aca9-087c9c45a697.png)
