### ISSUE TITLE
Monkeypox data for Slovenia

### ISSUE THREAD

**Issue by majazaloznik** [globaldothealth/monkeypox#40]
Hi there! Nice work on setting up the database. I'm part of the Slovenian covid data tracker [Sledilnik](https://covid-19.sledilnik.org/en/stats) and i've just used your template to start tracking the cases as they are reported in Slovenia:
[https://github.com/majazaloznik/monkeypox_globaldothealth
](https://github.com/majazaloznik/monkeypox_globaldothealth
)
Let me know if you need me to do sth different to simplify your pipeline. 

Keep up the good work!
m.

**Comment by ksewalk** [comment]
Thanks! This is now updated in the spreadsheet.

**Comment by majazaloznik** [comment]
Hi, just wanted to check your pipeline for Slovenia, you're checking the national institute of health (NIJZ) website manually? 

Because they have recently started overwriting their "news", so their archive is now lost. One of our colleagues is however taking regular snapshots of the website (several times a day, since there are multiple updates) as well as collating the data in a googlesheet, so please let us know if any of this might be helpful for you to simplify your pipeline.
