### ISSUE TITLE
Errors on Italian cases

### ISSUE THREAD

**Issue by vi-enne** [globaldothealth/monkeypox#44]
Your last update presents some errors regarding Italian cases: in particular, cases in Sicily have been discarded and not confirmed, while some cases in Lombardy are missing.

Please refer to this file
https://docs.google.com/spreadsheets/d/1_3f41fVeCj8Fy9yXEWLYtDzgyzBsRCTp--BOfUsGl8A

Thanks.

**Comment by ksewalk** [comment]
Reviewed by curation team. Thanks for logging!

**Comment by vi-enne** [comment]
You can continue consulting the file for updates on Italian cases.
