### ISSUE TITLE
Add case definitions for countries for which we have data

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#45]
- [ ] CHE  Switzerland
- [ ] FIN  Finland
- [ ] ARE  United Arab Emirates
- [ ] AUT  Austria
- [ ] PRT  Portugal
- [ ] SVN  Slovenia
- [ ] AUS  Australia
- [ ] BEL  Belgium
- [ ] ISR  Israel
- [ ] DEU  Germany
- [ ] DNK  Denmark
- [ ] SWE  Sweden
- [ ] CZE  Czechia
- [ ] GRC  Greece

**Comment by ksewalk** [comment]
We are no longer tracking.
