### ISSUE TITLE
Suggested reporting improvements for Spain

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#53]
Problem: Often times, Spain reports Monkeypox case counts at the country-level, without more granular detail. This makes it a challenge to disentangle suspected, confirmed, and discarded cases, specifically when large sums or increases are presented at the country-level, without geographic granularity. 

Our team is sometimes able to gather more detail from local reporting, and deduce through logic and media familiarity what case(s) are being referenced and what updates should be made to line list data, but these updates are time and resource intensive and subject to human error. Assumptions are made that may compromise the accuracy of the data.

Additionally, often times, the total number of samples that have been tested is reported, but may not include details of e.g. when the samples were tested, how many samples tested positive or negative, remaining number of suspected cases, or specific locations. So, to account for these changes, our team makes assumptions (for location, status, and other data) to match our database's case count balance to official reports.

Solution: Providing frequent and consistent case count updates of new (suspected/confirmed/discarded) cases, in addition to the total numbers of each, at the provincial/regional level -- a simple chart/ dashboard form -- would help to ensure timeliness and accuracy of data.

**Comment by aimeehan1** [comment]
Text has been captured and expanded in MPX blog post. Closing ticket.
