### ISSUE TITLE
Update map data more than 1x per day

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#56]
Currently data powering g.h map is updated 1x per day in the S3 bucket. 

Can we increase the frequency of when the data powering the map is updated to the S3?

**Comment by abhidg** [comment]
@ksewalk the map data should be updated at the same frequency as the S3 bucket, as it is from the same script, @maciekz1996 will the map always use the latest data? It is possible that latest.json is being cached, which then will show outdated results.

**Comment by maciekz1996** [comment]
@abhidg The map is updated every time the S3 bucket updates, this works fine. I think that @ksewalk wants us to increase the aggregation script frequency so that new data is available on the map more than once a day.

**Comment by abhidg** [comment]
@maciekz1996 aggregates script is at the same frequency as the script which fetches data from the Google spreadsheets, also just checked that the data in monkeypox-aggregates was updated with the last fetch.
