### ISSUE TITLE
g.h map confirmed vs. confirmed+suspected data 

### ISSUE THREAD

**Issue by ksewalk** [globaldothealth/monkeypox#57]
##Description

Currently the data the map is ingesting displays confirmed case total and confirmed+suspected case total as the same number
![Screen Shot 2022-06-02 at 2 58 50 PM](https://user-images.githubusercontent.com/20950416/171718501-f83aa42e-c079-4c0a-8e83-e054280ca394.png)
![Screen Shot 2022-06-02 at 2 58 56 PM](https://user-images.githubusercontent.com/20950416/171718515-3bd279d3-02a7-4091-97a2-3ec2e8136d8a.png)

## Definition of Done
Confirmed case total should only include confirmed case counts.

**Comment by abhidg** [comment]
@maciekz1996 PR #65 once merged will add a `confirmed_and_suspected` field to the aggregates JSON which you can use for the map

**Comment by abhidg** [comment]
@maciekz1996 PR #65  once merged will add a `confirmed` key to `total/latest.json` which you can use

**Comment by maciekz1996** [comment]
@abhidg Got it, thank you
