### ISSUE TITLE
Afghanistan, conflicting media reports

### ISSUE THREAD

**Issue by aimeehan1** [globaldothealth/monkeypox#59]
G.h curation team is monitoring conflicting media reports of suspected cases in Afghanistan - Nimroz (and possibly other) 
provinces. 

Reportedly, officials have rejected reports of suspected cases.  Suspected cases will be logged in tracker upon official acknowledgement. 
"The Ministry of Public Health of the Islamic Emirate of Afghanistan (IEA) has rejected reports of positive cases of monkeypox in some provinces of Afghanistan, saying that no cases of the disease have been registered so far."

https://www.ariananews.af/iea-denies-reports-of-monkeypox-in-afghanistan/
https://see.news/afghanistan-announces-earliest-2-monkeypox-cases/

**Comment by themistella** [comment]
Forward to @Dr. Kreamer, Please see my private message in your Twitter inbox on this topic. Regards. Themistella

**Comment by aimeehan1** [comment]
Afghanistan has been added to the internal watch list. Closing ticket.
