### ISSUE TITLE
WHO case report form

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#66]
Case report form was released for Monkeypox from WHO following the 2022 outbreak. Discussion here about which fields to add/adjust in Global.health monkeypox schema

https://www.who.int/publications/m/item/monkeypox-minimum-dataset-case-reporting-form-(crf) 

Docx: https://cdn.who.int/media/docs/default-source/blue-print/final_crf_mpx_1.docx?sfvrsn=5b09b570_1&download=true 

excel: https://cdn.who.int/media/docs/default-source/blue-print/monkeypox_crf_20220203.xls?sfvrsn=fb96ce9b_1

**Comment by tvarrelman** [comment]
[WHO_Gh_comparison_table.xlsx](https://github.com/globaldothealth/monkeypox/files/8863020/WHO_Gh_comparison_table.xlsx)

Here is a table that includes a comparison of WHO vs. Gh data fields. Green indicates no difference between WHO and Gh, yellow indicates that we have a similar field but that the entries are different, and red indicates that we do not have the data field in Gh. I have included notes on potential changes/additions to the Gh schema.

**Comment by Mougk** [comment]
My comments attached. @ksewalk next?

[WHO_Gh_comparison_table_MK.xlsx](https://github.com/globaldothealth/monkeypox/files/8863153/WHO_Gh_comparison_table_MK.xlsx)

**Comment by ksewalk** [comment]
Updated with comments. Next team review post-afternoon meeting.
[WHO_Gh_comparison_table_MK_KS.xlsx](https://github.com/globaldothealth/monkeypox/files/8871141/WHO_Gh_comparison_table_MK_KS.xlsx)

**Comment by BryanTegomoh** [comment]
[2022 Monkeypox Outbreak CRF_REDCap.pdf](https://github.com/globaldothealth/monkeypox/files/8884830/2022.Monkeypox.Outbreak.CRF_REDCap.pdf)
Terribly long but the CDC has a redcap survey for case reporting of monkeypox outbreak cases, which are a good primer to compare with... https://www.cdc.gov/poxvirus/monkeypox/pdf/2022-Monkeypox-Outbreak-Case-Report-REDCap-20220603.pdf.

**Comment by abhidg** [comment]
Line list is discontinued as of 2022-09-22
