### ISSUE TITLE
Watch Country List

### ISSUE THREAD

**Issue by aimeehan1** [globaldothealth/monkeypox#72]
Media has reported (suspected/confirmed/discarded) cases for a growing number of countries where our team of curators has not been able to verify data. We have placed these countries on an internal "watch list" and will update from verified sources, when/if available, including media reports of health official statements. 
1. Afghanistan
2. Kenya

**Comment by aimeehan1** [comment]
Greece removed from watchlist 2022-06-09. Added to tracker, ID 1563

**Comment by aimeehan1** [comment]
India removed from watchlist 2022-06-09. Added to tracker, ID 1566

**Comment by aimeehan1** [comment]
Bangladesh removed from watchlist 2022-06-11. Added to tracker, ID 1816

**Comment by aimeehan1** [comment]
Malawi removed from watchlist 2022-06-12. Added to tracker, ID 1840

**Comment by aimeehan1** [comment]
Somalia removed from watchlist 2022-06-24. Added to tracker, ID 4175 4176 4177

**Comment by aimeehan1** [comment]
Colombia removed from watchlist 2022-06-24. Added to tracker, ID 3977 3978 3979

**Comment by abhidg** [comment]
Line list is discontinued as of 2022-09-22
