### ISSUE TITLE
Proposal for using less lines by adding a [Case Count] column

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#74]
The idea of a line list with one line for each case makes sense as long as there is detailed information for each case. But the longer the monkeypox outbreak continues, the less we know about the individual cases. The information about the cases is now often given as an aggregate, e.g. 9 new cases in XY, with no further information about travel, age, hospitalisation, etc.

Instead of creating 9 identical rows, it would be shorter to add a [Case Count] column that would allow cases to be aggregated by country and confirmation date. And in the increasingly rare cases where there is additional information, it would still be possible to create an additional row with [Case Count]=1.

**Comment by vi-enne** [comment]
I agree with this idea.

In case it will be implemented, it would be better to announce it in a `CHANGELOG.md` file in advance, so that applications using this repo as a source can adapt.

**Comment by Mougk** [comment]
We will keep line list format for now (each row, one case) and revisit as more countries add aggregated counts.
