### ISSUE TITLE
Monkeypox in Ghana (West Africa)

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#75]
As far as I understand, monkeypox is endemic in West Africa. Does it make sense to mix case data from places where the virus is endemic with those where it isn’t?

**Comment by Mougk** [comment]
We are currently expanding the data collection to all countries reporting cases in 2022. That we believe would be more complete. Genomic data will help shed light on the connections between the outbreaks. See for more detail current visualisations on Nextstrain: https://nextstrain.org/monkeypox
