### ISSUE TITLE
Confirmation dates missing

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#77]
MISSING | CONFIRMATION | DATES
-- | -- | --
  | [ID] 1543 | Belgium
  | [ID] 1544 | Belgium
  | [ID] 1545 | Belgium
  | [ID] 1546 | Belgium
  | [ID] 1547 | Belgium
  | [ID] 1548 | Belgium
  | [ID] 1549 | Belgium
  | [ID] 1551 | Switzerland
  | [ID] 1552 | Switzerland
  | [ID] 1553 | UAE
  | [ID] 1554 | UAE
  | [ID] 1555 | UAE
  | [ID] 1556 | UAE
  | [ID] 1557 | UAE

**Comment by Mougk** [comment]
Fixed. thanks.
