### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Mougk** [globaldothealth/monkeypox#79]
- [x] Increase size of Figure 1
- [x] Harmonise fonts in all figures if not done already
- [x] Move Country up one column in Table 1 
- [x] "% difference in cases compared to last week" in first row of Table 1
- [x] Missing number of 'For X cases travel history location was unknown"
- [x] Figure 2 bold 
- [x] dot after sentence ending with "(Figure 3)"
- [x] Bold "Data accessibility and reproducibility" 
- [ ] Harmonise colours in all Figures.
- [x] Could we make Figures downloadable (or have a link at the top saying: "Figures and tables from this report can be downloaded from: XX"
- [x] Sizing of Figures in the report is a bit off.

**Comment by tvarrelman** [comment]
Consider expanding Figure 4 legend to include the following:

"Figure 4: Age and gender distribution of monkeypox confirmed cases in 2022. X% of confirmed cases include sufficient metadata to be included in this figure. Of these cases, X% include reported age ranges that span multiple age categories. Under such circumstances, counts are evenly distributed among the categories that capture the reported age range. "

I have the lines of code to calculate these percentages. 

@Mougk thoughts?

**Comment by aimeehan1** [comment]
@tvarrelman @Mougk Also discussed expanding the figure 3 legend or intro paragraph to more clearly explain purpose. Intent is to give the reader context on where genomic data is available, but also to bring awareness to the gap that exists between # cases and # sequences (UK example).

**Comment by abhidg** [comment]
Created issues for remaining, closing this
