### ISSUE TITLE
Harmonise figure colours

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#83]
Use figure colours as close to the blue palette that is used in the G.h map. @tvarrelman could the delay to confirmation graph be changed to use a blue-ish palette?

**Comment by tvarrelman** [comment]
@abhidg I will pull together a few alternative palettes

**Comment by tvarrelman** [comment]
New color palette added to Figure 2, and colors updated for Figure 3 & 4 to be G.h blue's.
