### ISSUE TITLE
Expand figure 3 legend or intro paragraph to more clearly explain purpose

### ISSUE THREAD

**Issue by abhidg** [globaldothealth/monkeypox#85]
@tvarrelman @Mougk Also discussed expanding the figure 3 legend or intro paragraph to more clearly explain purpose. Intent is to give the reader context on where genomic data is available, but also to bring awareness to the gap that exists between # cases and # sequences (UK example).

_Originally posted by @aimeehan1 in https://github.com/globaldothealth/monkeypox/issues/79#issuecomment-1152631181_

**Comment by Mougk** [comment]
Added sentence in our doc. @abhidg take a look.
