### ISSUE TITLE
+2 Cases (16 June) and +1 Case (17 June) in Switzerland and an Official Source with Updates on working days.

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#87]
![image](https://user-images.githubusercontent.com/73970205/174184546-e798178c-f43f-49c8-adde-ecf0bc05c2ff.png)
![image](https://user-images.githubusercontent.com/73970205/174324772-e554433f-0f98-4379-8ee7-736b039e8b9f.png)

[Official Source](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/affenpocken.html#573159143) with Updates on working days (5 pm CEST)

**Comment by TKrepo** [comment]
Do I really need to update this issue every day?

Switzerland is updating their page on working days around 5 pm CEST, so if someone of your team (or a script that scrapes the page) comes by around 6 pm, you’ll get their latest cases numbers. Since they’re only distinguishing between today’s cases and the total, you have to check every day in order not to miss a report.

**Comment by Mougk** [comment]
Thanks. We will keep an eye out.
