### ISSUE TITLE
Discrepancy in spain numbers

### ISSUE THREAD

**Issue by sanjredfield** [globaldothealth/monkeypox#90]
The following source reports the numbers in Madrid on a regular basis: https://www.europapress.es/madrid/noticia-suben-399-casos-viruela-mono-comunidad-otros-29-nuevos-positivos-20220615145853.html

The numbers reported for Madrid in the source used for this data set (https://www.sanidad.gob.es/en/profesionales/saludPublica/ccayes/alertasActual/alertaMonkeypox/docs/Informe_de_situacion_MPX_20220614.pdf) seem to be underreported, and haven't changed since the June 9 update (https://www.sanidad.gob.es/en/profesionales/saludPublica/ccayes/alertasActual/alertaMonkeypox/docs/Informe_de_situacion_MPX_20220609.pdf).

Is there a plan to use any additional data sources for Spain?

**Comment by themistella** [comment]
Hi all,
I have sent a message on the Spanish  Health Ministry's website to request the same statistics as those for Covid they publish in Telegram. Perhaps the more people ask, the more likely we'll get good numbers. In my experience with Spanish administrations, they usually reply promptly. There are two ways of contacting them, the webpage and email.
Kind regards to all.
Themistella

Email: oiac@sanidad.gob.es

Webpage:
https://www.sanidad.gob.es/oficinaInformacion/frmBuzonContacto.do

(Form does not exist in English, but most staff will understand or pass on to an English speaker. Select Madrid for autonomous community CCAA, Sugerencia, and Estadísticas for Sección, write Estadísticas in Asunto, and your request in Texto)

**Comment by aimeehan1** [comment]
Hello @themistella @sanjredfield. 
The G.h team has been closely following the Monkeypox outbreak in Spain. Spain's Ministry of Health has commented that they will update their figures twice per week, Tuesday and Friday. The latest official report from 2022-06-14 is 313 confirmed cases, which matches the number of cases reported in our tracker. 

https://www.sanidad.gob.es/en/profesionales/saludPublica/ccayes/alertasActual/alertaMonkeypox/docs/Informe_de_situacion_MPX_20220614.pdf

We also have identified large discrepancies in case reporting within the media, specifically for Madrid, and appreciate your help to resolve. 
Thank you for your contributions.

**Comment by sanjredfield** [comment]
As recommended by @themistella, I emailed the health ministry, and received a response with a link to the official announcement from June 14.

**Comment by themistella** [comment]
Hi all ,

I have received the same canned reply as yourselves. So I replied that this was not what I asked, that I wanted as much information as for the Covid updates, and requested they forward my request to the Head of the Statistics Department, giving them the link to the Covid example:

https://www.sanidad.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/Actualizacion_608_COVID-19.pdf

We'll see. The Spaniards are pretty good with informatics and cross-referencing all the national, regional and international databases. You can't twist a toe or buy a fridge without your ID number here, and the whole country will know about it 🥺 So hopefully we'll get better information at some point. If not, I might send them a registered letter in the future 😆

Have a nice weekend. Kind regards to all.
Themistella

**Comment by aimeehan1** [comment]
Thank you all for the follow-up. Case counts have been updated to match official MOH reporting as of 2022-06-17. Updates are likely expected on Tuesdays and Fridays. Closing ticket.

**Comment by themistella** [comment]
Hi all,

Received another canned reply, which also adds that they confirm updating on Tuesdays and Fridays, therefore there will be an update today 21st June 2022. Also, they gave another piece of information:

(Google translation)

"...an informative campaign is being worked on for social networks in different formats, videos, posters, etc. The idea is to be able to publish it as soon as possible..."

Kind regards to all.
Themistella
