### ISSUE TITLE
+2 (16 June), +1 (17 June), and +9 Cases (20 June) in Switzerland and an Official Source with Updates on working days.

### ISSUE THREAD

**Issue by TKrepo** [globaldothealth/monkeypox#97]
In your Google-Sheet there haven’t been any updates for Switzerland since 15 June.

![image](https://user-images.githubusercontent.com/73970205/174644530-b1cbe618-e220-42bc-89dc-058515c6098a.png)

![image](https://user-images.githubusercontent.com/73970205/174184546-e798178c-f43f-49c8-adde-ecf0bc05c2ff.png)
![image](https://user-images.githubusercontent.com/73970205/174324772-e554433f-0f98-4379-8ee7-736b039e8b9f.png)
![image](https://user-images.githubusercontent.com/73970205/174643972-2652807b-40b3-4e2a-9376-b17cb7956f7f.png)

[Official Source](https://www.bag.admin.ch/bag/en/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/affenpocken.html#573159143) with Updates on working days (5 pm CEST)

**Comment by TKrepo** [comment]
No, there weren’t 12 new cases “confirmed” today. Only 9. The other 3 are from the past week (see above).
![image](https://user-images.githubusercontent.com/73970205/174647881-48b20f95-29f1-4cf5-b233-8ad15bf8599d.png)

**Comment by aimeehan1** [comment]
@TKrepo Hello, thank you for the additional detail for date_confirmation. Data is updated in tracker.

**Comment by TKrepo** [comment]
Almost there.
June 16: +2
June 17: +1
Not to nitpick, but if you're dedicating a line to each case, why not get the dates correct?

![image](https://user-images.githubusercontent.com/73970205/174668085-818bae2f-f6db-4bd0-8e40-284274aa925d.png)
