### ISSUE TITLE
Review Argentina Case count

### ISSUE THREAD

**Issue by mlozano1602** [globaldothealth/monkeypox#99]
ECDC MPX reported on June 15, 2022 a total of 5 confirmed cases in Argentina. 
https://www.ecdc.europa.eu/en/news-events/epidemiological-update-monkeypox-multi-country-outbreak-15-june
Currently only one case is read into the report.

The cases reported in the rows with ID 2334 and 2335 are not confirmed by the Argentine Ministry of Health and should be removed. 

Argentina reports a total of 3 confirmed cases and one suspected case as of June 21

**Comment by aimeehan1** [comment]
2022-06-23, ID 3368 has now been confirmed as the 4th case in Argentina. 

The ECDC MPX report, Worldwide update section, reported 5 cases in Argentina.  However, G.h has updated the status for ID 2334 and 2335 to suspected [to account for potential differences in case definitions and reporting or error]. 

@mlozano1602 We appreciate your contributions! 
Closing ticket.
